bracketSpacing: true
plugins:
  - "prettier-plugin-solidity"
printWidth: 120
proseWrap: "always"
singleQuote: false
tabWidth: 2
trailingComma: "all"

overrides:
  - files: "contrats/*.sol"
    options:
      compiler: "0.8.17"
      parser: "solidity-parse"
      tabWidth: 4
